[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"

[build]
  publish = "dist"
  command = "npm i && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
