name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm i --no-save

      - name: Build for github.io Pages
        run: npm run build
        if: ${{ endsWith(github.event.repository.name, 'github.io') }}

      - name: Build for Project Pages
        run: BASE_URL=/${{ github.event.repository.name }}/ npm run build
        if: ${{ !endsWith(github.event.repository.name, 'github.io') }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/client
